# Pre-commit hooks configuration
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: detect-private-key

  # Go-specific hooks
  - repo: local
    hooks:
      - id: go-fmt
        name: Go Format
        entry: bash -c 'cd local-k8s-cluster-go && go fmt ./...'
        language: system
        files: '\.go$'
        pass_filenames: false

      - id: go-imports
        name: Go Imports
        entry: bash -c 'cd local-k8s-cluster-go && goimports -w .'
        language: system
        files: '\.go$'
        pass_filenames: false

      - id: go-vet
        name: Go Vet
        entry: bash -c 'cd local-k8s-cluster-go && go vet ./...'
        language: system
        files: '\.go$'
        pass_filenames: false

      - id: go-mod-tidy
        name: Go Mod Tidy
        entry: bash -c 'cd local-k8s-cluster-go && go mod tidy'
        language: system
        files: 'go\.(mod|sum)$'
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'cd local-k8s-cluster-go && golangci-lint run --fix'
        language: system
        files: '\.go$'
        pass_filenames: false

      - id: go-tests
        name: Go Tests
        entry: bash -c 'cd local-k8s-cluster-go && go test -short ./...'
        language: system
        files: '\.go$'
        pass_filenames: false

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [optional-scope]

  # Markdown and documentation
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]