# golangci-lint configuration
run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec

linters-settings:
  govet:
    enable-all: true
  revive:
    severity: warning

issues:
  exclude-use-default: false